apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - name: ocr-container
        image: ocr-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  selector:
    app: ocr
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: NodePort
