apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translation
  template:
    metadata:
      labels:
        app: translation
    spec:
      containers:
      - name: translation-container
        image: translation-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  selector:
    app: translation
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
